### ISSUE TITLE
关于数据集的选择和制作问题

### ISSUE THREAD

**Issue by zhengjiangw** [LeslieZhoa/tensorflow-MTCNN#8]
你好，小白有一个脑残问题，既然lfw数据集既有bbox数据，也有landmark数据，为什么要分别用wider_face数据集来训练bbox，lfw来训练landmark呢？ 而且这样就造成了P-net的训练过程中每条样本就只能计算一种损失，期待您的回复

**Comment by LeslieZhoa** [comment]
Hi @RondaRousey ,这种就是多任务训练，损失函数计算会根据label值来分别计算landmark和bbox,通俗来讲就是各管各的活，一起干效果更好，如果数据既有landmark又有bbox，单凭label值很难区分两种数据，就谈不上是多任务了，只能算是单任务多输出而已，而且这样对样本的要求也比较大。
希望可以帮助到你！

**Comment by lunar-r** [comment]
lunar@lunar-virtual-machine:~/PycharmProjects/tensorflow_mtcnn/preprocess$ python gen_hard_example.py 24
2019-05-12 09:33:06.690596: I tensorflow/core/platform/cpu_feature_guard.cc:140] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
载入数据
8247it [2:47:10,  1.26it/s]Traceback (most recent call last):
  File "gen_hard_example.py", line 193, in <module>
    main(parse_arguments(sys.argv[1:]))
  File "gen_hard_example.py", line 70, in main
    detectors,_=mtcnn_detector.detect_face(test_data)
  File "../detection/MtcnnDetector.py", line 87, in detect_face
    boxes, boxes_c, landmark = self.detect_rnet(im, boxes_c)
  File "../detection/MtcnnDetector.py", line 181, in detect_rnet
    cls_scores, reg, _ = self.rnet_detector.predict(cropped_ims)
  File "../detection/detector.py", line 63, in predict
    return np.concatenate(cls_prob_list, axis=0), np.concatenate(bbox_pred_list, axis=0), np.concatenate(landmark_pred_list, axis=0)
ValueError: need at least one array to concatenate

嗨@LeslieZhoa，请问一下这个报错如何解决？需要将axis改为1嘛？

**Comment by woshizhangcheng** [comment]
> Hi @RondaRousey ,这种就是多任务训练，损失函数计算会根据label值来分别计算landmark和bbox,通俗来讲就是各管各的活，一起干效果更好，如果数据既有landmark又有bbox，单凭label值很难区分两种数据，就谈不上是多任务了，只能算是单任务多输出而已，而且这样对样本的要求也比较大。
> 希望可以帮助到你！
你好， 现在retinaFace给出了wider_face上的landmark信息，是否可以不使用lfw数据集了，直接用wider_face训练
